[package]
name = "trustml"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray-linalg = "0.16"
serde = { version = "1.0", features = ["derive"] }
pyo3 = { version = "0.18", features = ["extension-module"] }
